/**
 * Built-in jurisdiction profile stubs (E9 Jurisdiction).
 * Config-driven, versioned. No live tax rates or law logic.
 * All values are deterministic stubs for the foundation; real config is
 * stored per-tenant and can override any field.
 *
 * IMPORTANT: These stubs do NOT constitute legal or tax advice.
 * The CA agent must always surface the complianceDisclaimer to users.
 */
import type { CountryCode, JurisdictionProfile } from "./types.js";

const GLOBAL_DISCLAIMER =
  "This output is generated by an AI assistant and does not constitute legal, tax, or financial advice. " +
  "Always consult a licensed professional in the relevant jurisdiction before acting on any information provided.";

const BASE_CAPABILITIES = [
  "finance:read",
  "finance:draft",
  "finance:summarize",
  "finance:classify",
];

const BASE_RESTRICTED = [
  "finance:file_government",
  "finance:transfer_funds",
  "finance:sign_document",
];

export const JURISDICTION_PROFILES: Record<CountryCode, JurisdictionProfile> = {
  IN: {
    countryCode: "IN",
    countryName: "India",
    currency: "Indian Rupee",
    currencyCode: "INR",
    fiscalYearStart: "04-01",
    fiscalYearEnd: "03-31",
    taxIdentifierLabels: {
      primary: "PAN",
      employer: "TAN",
      gst: "GSTIN",
      customs: "IEC",
    },
    complianceDisclaimer:
      GLOBAL_DISCLAIMER +
      " Indian tax law is complex and changes frequently. GST, TDS, and income tax rules " +
      "require professional CA/CS advice. This tool does not file returns with the MCA, IT Dept, or GSTN.",
    documentTypes: [
      "GST Invoice", "Tax Invoice", "Credit Note", "Debit Note",
      "Form 16", "Form 26AS", "Balance Sheet", "P&L Statement",
      "ITR", "GSTR-1", "GSTR-3B", "TDS Return",
    ],
    reportingPeriods: ["Q1 (Apr–Jun)", "Q2 (Jul–Sep)", "Q3 (Oct–Dec)", "Q4 (Jan–Mar)", "Annual (Apr–Mar)"],
    approvalRequirements: [
      "gst_filing", "itr_submission", "tds_payment", "roc_filing", "mca_form",
    ],
    dataRetentionClass: "8-year",
    allowedAgentCapabilities: [...BASE_CAPABILITIES, "finance:gst_reconcile", "finance:tds_compute_stub"],
    restrictedActions: [...BASE_RESTRICTED, "finance:gstn_file", "finance:itr_file", "finance:mca_file"],
  },

  US: {
    countryCode: "US",
    countryName: "United States",
    currency: "US Dollar",
    currencyCode: "USD",
    fiscalYearStart: "01-01",
    fiscalYearEnd: "12-31",
    taxIdentifierLabels: {
      primary: "EIN",
      individual: "SSN / ITIN",
      sales_tax: "Sales Tax ID",
      state: "State Tax ID",
    },
    complianceDisclaimer:
      GLOBAL_DISCLAIMER +
      " US federal and state tax law varies significantly by entity type and state. " +
      "This tool does not file returns with the IRS, state revenue departments, or SEC.",
    documentTypes: [
      "Form W-2", "Form 1099", "Form 1040", "Form 1120", "Form 1065",
      "Schedule K-1", "Balance Sheet", "Income Statement", "Form 941",
      "Form W-9", "Sales Invoice", "Purchase Order",
    ],
    reportingPeriods: ["Q1 (Jan–Mar)", "Q2 (Apr–Jun)", "Q3 (Jul–Sep)", "Q4 (Oct–Dec)", "Annual (Jan–Dec)"],
    approvalRequirements: [
      "irs_filing", "state_return_filing", "payroll_deposit", "w2_issuance", "1099_filing",
    ],
    dataRetentionClass: "7-year",
    allowedAgentCapabilities: [...BASE_CAPABILITIES, "finance:payroll_compute_stub", "finance:1099_classify"],
    restrictedActions: [...BASE_RESTRICTED, "finance:irs_file", "finance:state_file", "finance:sec_report"],
  },

  CA: {
    countryCode: "CA",
    countryName: "Canada",
    currency: "Canadian Dollar",
    currencyCode: "CAD",
    fiscalYearStart: "01-01",
    fiscalYearEnd: "12-31",
    taxIdentifierLabels: {
      primary: "BN (Business Number)",
      gst_hst: "GST/HST Number",
      payroll: "Payroll Program Account",
      individual: "SIN",
    },
    complianceDisclaimer:
      GLOBAL_DISCLAIMER +
      " Canadian tax law is administered federally (CRA) and provincially. " +
      "GST/HST rules vary by province. This tool does not file returns with CRA or provincial agencies.",
    documentTypes: [
      "T4 Slip", "T5 Slip", "T2 Return", "T1 Return", "GST/HST Return",
      "T4A Slip", "Invoice", "Receipt", "Financial Statement",
      "T2200", "ROE (Record of Employment)",
    ],
    reportingPeriods: ["Q1 (Jan–Mar)", "Q2 (Apr–Jun)", "Q3 (Jul–Sep)", "Q4 (Oct–Dec)", "Annual (Jan–Dec)"],
    approvalRequirements: [
      "cra_filing", "gst_hst_remittance", "payroll_remittance", "t4_issuance", "provincial_return",
    ],
    dataRetentionClass: "7-year",
    allowedAgentCapabilities: [...BASE_CAPABILITIES, "finance:gst_hst_classify", "finance:t4_draft_stub"],
    restrictedActions: [...BASE_RESTRICTED, "finance:cra_file", "finance:provincial_file"],
  },

  GB: {
    countryCode: "GB",
    countryName: "United Kingdom",
    currency: "Pound Sterling",
    currencyCode: "GBP",
    fiscalYearStart: "04-06",
    fiscalYearEnd: "04-05",
    taxIdentifierLabels: {
      primary: "UTR (Unique Taxpayer Reference)",
      vat: "VAT Registration Number",
      employer: "PAYE Reference",
      company: "Companies House Number",
    },
    complianceDisclaimer:
      GLOBAL_DISCLAIMER +
      " UK tax law is administered by HMRC. VAT, PAYE, and Corporation Tax rules require " +
      "professional advice. This tool does not file returns with HMRC or Companies House.",
    documentTypes: [
      "VAT Return", "Self Assessment", "Corporation Tax Return", "P60", "P45",
      "P11D", "Payslip", "Invoice", "Credit Note", "Annual Accounts",
      "Confirmation Statement", "Balance Sheet",
    ],
    reportingPeriods: ["Q1 (Apr–Jun)", "Q2 (Jul–Sep)", "Q3 (Oct–Dec)", "Q4 (Jan–Mar)", "Annual (Apr–Apr)"],
    approvalRequirements: [
      "hmrc_filing", "vat_return", "paye_rtis", "companies_house_filing", "sa_return",
    ],
    dataRetentionClass: "6-year",
    allowedAgentCapabilities: [...BASE_CAPABILITIES, "finance:vat_classify", "finance:paye_compute_stub"],
    restrictedActions: [...BASE_RESTRICTED, "finance:hmrc_file", "finance:companies_house_file"],
  },

  GLOBAL: {
    countryCode: "GLOBAL",
    countryName: "Global / Unspecified",
    currency: "Unspecified",
    currencyCode: "USD", // safe default for display only
    fiscalYearStart: "01-01",
    fiscalYearEnd: "12-31",
    taxIdentifierLabels: {},
    complianceDisclaimer:
      GLOBAL_DISCLAIMER +
      " No specific jurisdiction has been configured for this agent or task. " +
      "All outputs are generic and must be validated by a licensed professional in the applicable jurisdiction " +
      "before any action is taken.",
    documentTypes: ["Invoice", "Receipt", "Financial Statement", "Balance Sheet"],
    reportingPeriods: ["Annual"],
    approvalRequirements: ["any_government_filing", "any_fund_transfer", "any_document_signing"],
    dataRetentionClass: "7-year",
    allowedAgentCapabilities: BASE_CAPABILITIES,
    restrictedActions: [
      ...BASE_RESTRICTED,
      "finance:jurisdiction_specific",
      "finance:tax_advice",
      "finance:legal_advice",
    ],
  },
};

/**
 * Resolve the profile for a country code. Returns GLOBAL fallback with an
 * enhanced disclaimer if the code is not explicitly configured. The CA agent
 * must always require an explicit jurisdiction — the GLOBAL fallback is a
 * safe degradation, not a default assumption.
 */
export function resolveProfile(
  countryCode: CountryCode,
  overrides?: Partial<JurisdictionProfile>,
): JurisdictionProfile {
  const base = JURISDICTION_PROFILES[countryCode] ?? JURISDICTION_PROFILES.GLOBAL;
  if (!overrides) return base;
  return {
    ...base,
    ...overrides,
    taxIdentifierLabels: { ...base.taxIdentifierLabels, ...overrides.taxIdentifierLabels },
    allowedAgentCapabilities: overrides.allowedAgentCapabilities ?? base.allowedAgentCapabilities,
    restrictedActions: overrides.restrictedActions ?? base.restrictedActions,
    documentTypes: overrides.documentTypes ?? base.documentTypes,
    reportingPeriods: overrides.reportingPeriods ?? base.reportingPeriods,
    approvalRequirements: overrides.approvalRequirements ?? base.approvalRequirements,
  };
}
